-- MySQL Script generated by MySQL Workbench
-- Tue Apr 14 13:17:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendedor` (
  `cpf` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `rg` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `whatsapp` INT(9) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Description` TEXT(150) NOT NULL,
  `value` DECIMAL(45) NOT NULL,
  `Vendedor_cpf` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_Produto_Vendedor_idx` (`Vendedor_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Vendedor`
    FOREIGN KEY (`Vendedor_cpf`)
    REFERENCES `mydb`.`Vendedor` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
